alter table public.farming_fields
  add column if not exists plant_count integer;

alter table public.farming_fields
  drop constraint if exists farming_fields_plant_count_positive;

alter table public.farming_fields
  add constraint farming_fields_plant_count_positive
  check (plant_count is null or plant_count > 0);

create table if not exists public.calorie_stores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.calorie_store_foods (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.calorie_stores(id) on delete cascade,
  food_id text not null check (char_length(food_id) between 1 and 160),
  price numeric(14, 4) check (price is null or price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, food_id)
);

create index if not exists calorie_store_foods_store_id_idx on public.calorie_store_foods(store_id);

alter table public.calorie_stores enable row level security;
alter table public.calorie_store_foods enable row level security;

grant select, insert, update, delete on table public.calorie_stores to anon;
grant select, insert, update, delete on table public.calorie_store_foods to anon;
grant usage, select on sequence public.calorie_stores_id_seq to anon;
grant usage, select on sequence public.calorie_store_foods_id_seq to anon;

create policy "members can read calorie stores" on public.calorie_stores for select to anon using ((select private.has_workspace_access()));
create policy "members can add calorie stores" on public.calorie_stores for insert to anon with check ((select private.has_workspace_access()));
create policy "members can update calorie stores" on public.calorie_stores for update to anon using ((select private.has_workspace_access())) with check ((select private.has_workspace_access()));
create policy "members can delete calorie stores" on public.calorie_stores for delete to anon using ((select private.has_workspace_access()));

create policy "members can read calorie store foods" on public.calorie_store_foods for select to anon using ((select private.has_workspace_access()));
create policy "members can add calorie store foods" on public.calorie_store_foods for insert to anon with check ((select private.has_workspace_access()));
create policy "members can update calorie store foods" on public.calorie_store_foods for update to anon using ((select private.has_workspace_access())) with check ((select private.has_workspace_access()));
create policy "members can delete calorie store foods" on public.calorie_store_foods for delete to anon using ((select private.has_workspace_access()));
